examples/data-sources/utils_stack_config_yaml/data-source.tf, internal/stack/stack_processor.go
* Add `component` attribute to the outputs of Terraform components that inherit from a base component
* Useful for Terraform modules that use the provider to know if a component has inherited `vars` from a base component
* Used in remote backends to decide whether or not to add the component name to the Terraform workspace name
```
aurora-postgres:
vars:
instance_type: db.r4.large
cluster_size: 2
aurora-postgres-2:
component: aurora-postgres
vars:
cluster_size: 3
instance_type: db.r4.xlarge
```
```
"aurora-postgres" = {
"backend" = {
"acl" = "bucket-owner-full-control"
"bucket" = "eg-uw2-root-tfstate"
"dynamodb_table" = "eg-uw2-root-tfstate-lock"
"encrypt" = true
"key" = "terraform.tfstate"
"region" = "us-west-2"
"role_arn" = "arn:aws:iam::XXXXXXXXXXXX:role/eg-gbl-root-terraform" …
```
=> Add `component` attribute to the outputs of Terraform components that inherit from a base component

CHANGELOG.md, docs/terraform.md, examples/data-sources/utils_deep_merge_json/data-source.tf, examples/data-sources/utils_deep_merge_yaml/data-source.tf, examples/data-sources/utils_stack_config_yaml/data-source.tf, examples/data-sources/utils_stack_config_yaml/stacks/globals.yaml, examples/data-sources/utils_stack_config_yaml/stacks/uw2-dev.yaml, examples/data-sources/utils_stack_config_yaml/stacks/uw2-globals.yaml, examples/data-sources/utils_stack_config_yaml/stacks/uw2-prod.yaml, examples/data-sources/utils_stack_config_yaml/stacks/uw2-staging.yaml, examples/data-sources/utils_stack_config_yaml/stacks/uw2-uat.yaml, go.mod, go.sum, internal/convert/json.go, internal/convert/json_test.go, internal/convert/map.go, internal/convert/slice.go, internal/convert/yaml.go, internal/convert/yaml_test.go, internal/merge/merge.go, internal/merge/merge_test.go, internal/stack/stack_processor.go, internal/stack/stack_processor_test.go, main.go
* Add `settings` sections to `data_source_stack_config_yaml` data source to provide settings for Terraform and helmfile components
* Add `env` sections to `data_source_stack_config_yaml` data source to provide ENV vars for Terraform and helmfile components
* Workaround for a deep-merge bug in `mergo.Merge()`
* Fix failing tests
* Add `stack_processor_test.go`
* `settings` sections are deep-merged and used for consumption by external services (e.g. for Spacelift and Terraform Cloud Terraform modules)
*  `env` sections are deep-merged and used to specify ENV vars for consumption by external services (e.g. for Spacelift and Terraform Cloud)
* Workaround for a deep-merge bug in `mergo.Merge()`. When deep-merging slice of maps in a `for` loop, 
`mergo` modifies the source of the previous loop …
=> Add `settings` and `env` sections. Workaround for a deep-merge bug in `mergo.Merge()`

README.md, README.yaml, internal/convert/id.go, internal/provider/data_source_deep_merge_json.go, internal/provider/data_source_deep_merge_yaml.go, internal/provider/data_source_stack_config_yaml.go
- Ensure results have unique IDs
- Typically a component will have multiple instances of this module, and to avoid confusion they should have unique ids.
=> Ensure results have unique IDs

README.md, README.yaml, examples/data-sources/utils_stack_config_yaml/data-source.tf, internal/provider/data_source_stack_config_yaml.go, internal/stack/stack_processor.go, internal/stack/stack_processor_test.go
* [stack_processor]: Add `process_stack_deps` input var to the `stack_config` data source
* Make the settings configurable (`false` by default)
* Not all provider invocations need to process all stack dependencies for the components (e.g. Spacelift module needs it, `remote-state` does not)
* Makes invocations without processing stack dependencies 2-3 times faster
=> [stack_processor]: Add `process_stack_deps` input var to the `stack_config` data source

.github/workflows/auto-release.yml
- Set `auto-release` to run on push to `main` branch
- Was set to run on push to `master` branch, but this repo does not have a `master` branch, so it never ran
=> Fix target branch of workflow

internal/convert/id.go
- Use thread safe function to generate object IDs
- Terraform performs actions in parallel, so using a global variable is not safe
```
panic: d.nx != 0
plugin.terraform-provider-utils_v0.4.2: 
plugin.terraform-provider-utils_v0.4.2: goroutine 61 [running]:
plugin.terraform-provider-utils_v0.4.2: crypto/sha1.(*digest).checkSum(0xc000497778, 0x0, 0x0, 0xec943cb500000000)
```
=> Use thread safe function

.github/workflows/release.yml
* Updates github release action to use 1.16
Do the `go.sum` and `go.mod` files also need to be updated ?
* The go releaser worked for me locally because I'm using go 1.16 but did not work in github action as go 1.15 still does not allow darwin arm releases.
* Previous PR https://github.com/cloudposse/terraform-provider-utils/pull/38
* Closes https://github.com/cloudposse/terraform-provider-utils/issues/33
=> Change go version in release action

README.md, internal/spacelift/spacelift_stack_processor.go
* [spacelift_stack_processor]: Update Spacelift labels
* For each component (which is a Spacelift stack), we need to apply only the `folder: env/stage` label. No need for `folder: env` label since if both are applied, Spacelift double-counts components in each folder (and no component exists directly in `env`, they are under `env/stage`)
=> [spacelift_stack_processor]: Update Spacelift labels

examples/data-sources/utils_spacelift_stack_config/stacks/uw2-dev.yaml, examples/data-sources/utils_spacelift_stack_config/stacks/uw2-prod.yaml, examples/data-sources/utils_spacelift_stack_config/stacks/uw2-staging.yaml, examples/data-sources/utils_spacelift_stack_config/stacks/uw2-uat.yaml, internal/spacelift/spacelift_stack_processor.go, internal/spacelift/spacelift_stack_processor_test.go
* [spacelift_stack_processor]: Add explicit labels to Spacelift stacks defined in YAML configs
* Allow adding custom labels to each stack's Spacelift config
* This will allow 
- adding explicit dependencies (files) to each stack (if the files change, the stack will be triggered)
- creating complex workflows where one Spacelift stack depends on others
Given this config with the custom label:
```
aurora-postgres-2:
settings:
spacelift:
workspace_enabled: true
labels:
- "deps:config/secrets/dev-internal-secrets.yml"
```
the provider generates the following list of all labels for the component (including the custom label):
```
labels:
- import:stacks/catalog/eks-defaults.yaml
- import:stacks/catalog/rds-defaults.yaml
- import:stacks/catalog/s3-defaults.yaml
- import:stacks/globals.yaml
- …
```
=> [spacelift_stack_processor]: Add explicit labels to Spacelift stacks

examples/data-sources/utils_spacelift_stack_config/stacks/catalog/eks-app-defaults.yaml, examples/data-sources/utils_spacelift_stack_config/stacks/catalog/eks-defaults.yaml, examples/data-sources/utils_stack_config_yaml/stacks/catalog/eks-app-defaults.yaml, examples/data-sources/utils_stack_config_yaml/stacks/catalog/eks-defaults.yaml, internal/stack/stack_processor.go
* Fix imports
* Fix deadlocks
* Add validation
* Improve error messages
* Use absolute import paths (from the base path, which is usually `stacks`) even inside subfolders. 
It's more clear to use 
```  
import:
- catalog/services/*.yaml
```
than
```
import:
- services/*.yaml
```
if `/services/*.yaml` is a subfolder of `catalog`.
* Fix deadlock - if any import pointed to an incorrect path, the `WaitGroup` was waiting forever causing process hang/freeze. Now it checks if the import path exists and points to any files, and throws an error otherwise
* Add validation and improve error messages for situations like these:
```
Invalid import in config file ../stacks/catalog/eks-app-defaults.yaml. 
No config files found for import: catalog/services/s1/*.yaml
Invalid import in config file …
```
=> [stack_processor]: Fix imports. Fix deadlocks. Add validation. Improve error messages

internal/convert/yaml.go
Hey, thanks for this provider. We use it to do a merge of two Helm value files (example below) - one with a set of default values and one with user overrides/additions. In cases when user does not set any overriding values, the second input is empty (`var.values`).
Passing an empty string (or nil) to the inputs, causes the provider to crash. I'm attaching the panic log below.
```
data "utils_deep_merge_yaml" "values" {
count = var.enabled ? 1 : 0
input = [
local.values,
var.values
]
}
```
```
goroutine 34 [running]:
github.com/cloudposse/terraform-provider-utils/internal/convert.YAMLSliceOfInterfaceToSliceOfMaps(0xc000576660, 0x2, 0x2, 0xb49b80, 0xc000338408, 0xd4ad01, 0xc00033a7c0, 0xc03b6ee8763240ae)
github.com/cloudposse/terraform-provider-utils/internal/convert/yaml.go:20 +0x1f4 …
```
=> Fix YAML conversion with empty strings

internal/component/component_processor.go
* Update component processor
* To calculate terraform workspace, use the logical stack name instead of physical folder path
=> Update component processor

go.mod, go.sum
* Bump `atmos` version
* Fix concurrency issues with `doublestar.Glob`
* https://github.com/cloudposse/atmos/pull/71
* https://github.com/cloudposse/geodesic/pull/734#issuecomment-936265546
=> Bump `atmos` version

examples/data-sources/utils_spacelift_stack_config/utils_spacelift_stack_config_test.go, go.mod, go.sum, internal/spacelift/spacelift_stack_processor_test.go, internal/stack/stack_processor_test.go
* Bump `atmos` version
* Disable component inheritance chain for now
* While it's working in all the tests, and in 99% of the real infra stacks, some edge cases of stack config are not handled correctly and cause gorotine panic
* All edge cases will be tested and fixed in a consecutive PR
=> Bump `atmos` version. Disable component inheritance chain

examples/data-sources/utils_component_config/data-source.tf, go.mod, go.sum, internal/provider/data_source_component_config.go
* Update `atmos`
* Add `ignore_errors` input to `data_source_component_config`
* Use latest code from `atmos` with new features and bug fixes
* `data_source_component_config` is used to read remote state of components. Sometimes we want to ignore errors if a component does not exist in a stack and just return an empty value
* https://github.com/cloudposse/atmos/pull/120
=> Update `atmos`. Add `ignore_errors` input to `data_source_component_config`

.github/workflows/validate-codeowners.yml, examples/complete/stacks/catalog/terraform/test-component.yaml, examples/data-sources/utils_spacelift_stack_config/utils_spacelift_stack_config_test.go, go.mod, go.sum, internal/component/component_processor_test.go, internal/spacelift/spacelift_stack_processor_test.go
* Update `atmos`
* Update tests
* Terraform workspace for remote state for derived components in subfolders was calculated differently from the terraform state for `atmos` terraform commands (leading to errors/failures in `remote-state.tf` for derived components in subfolders
* Use the same code to calculate terraform workspace for all CLI commands: `terraform plan/apply`, `describe component`, and for `component-Processor` which is used in `remote-state` and `backend`
* https://github.com/cloudposse/atmos/pull/121
=> Update `atmos`. Update tests

examples/data-sources/utils_component_config/atmos.yaml, examples/data-sources/utils_spacelift_stack_config/atmos.yaml, go.mod, go.sum, internal/component/atmos.yaml, internal/spacelift/atmos.yaml
* Update `atmos`
* Add `init_run_reconfigure` CLI config
* Update `stack_name_pattern`
* `init_run_reconfigure` CLI config allows enabling/disabling the `-reconfigure` argument for `terraform init` when running it before running other terraform commands
* Don't use the default `stack_name_pattern` because it used `{tenant}` which is not available for all clients
* Running `terraform plan` and `terraform workspace` on abstract components creates terraform workspaces which is not needed
=> Update `atmos`. Add `init_run_reconfigure` CLI config. Update `stack_name_pattern`

.goreleaser.yml, examples/complete/stacks/tenant1/ue2/test1.yaml, examples/data-sources/utils_spacelift_stack_config/utils_spacelift_stack_config_test.go, go.mod, go.sum, internal/component/component_processor_test.go, internal/spacelift/spacelift_stack_processor_test.go, internal/stack/stack_processor_test.go
* Update `atmos` and tests
* Support dashes `-` in the tenant, environment and stage names
* The old `atmos` supported dashes in the names (because it was filename-based, not logical stack name based) 
* Some clients want to name tenants/environments/stages with dashes in the names (and some already have it, so we need to support that when converting from the old to the new `atmos`)
* https://github.com/cloudposse/atmos/pull/143
=> Update `atmos` and tests

.github/workflows/release.yml
- Fix `go` version for building release artifacts
- Need to build with `go` version 1.20, not 1.2
=> Fix golang version for building release artifacts

.github/workflows/test.yml
* Install terraform
* New Github action public runners do not have terraform by default
* https://github.com/gruntwork-io/terratest/issues/1388
=> Install terraform
